### ISSUE TITLE
404 Error: Unable to access team subscription link

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#1]
# Issue Description
When trying to complete the first task in the Git section (line 51) of hw.txt, I encountered a 404 error while attempting to subscribe to colleagues.

## Steps to Reproduce
1. Open hw.txt from the repository https://github.com/SENATOROVAI/DataScience-Nayil/blob/main/hw.txt
2. Navigate to Git section (line 51) -  1)подписаться на коллег https://github.com/orgs/SENATOROVAI/teams/senatorov-team
3. Click on the link: https://github.com/orgs/SENATOROVAI/teams/senatorov-team
![image](https://github.com/user-attachments/assets/a897c8d2-7392-4317-afc5-aad8ac4f2625)
[hw.txt](https://github.com/user-attachments/files/17473505/hw.txt)

## Current Behavior
- Link returns 404 error
- Unable to access team subscription page

## Expected Behavior
- Link should direct to the team subscription page
- Should be able to subscribe to colleagues

## File Reference
I've attached the hw.txt file for better context of the issue. The problematic line can be found on line 51.

## Additional Context
- File: hw.txt
- Line number: 51
- Section: Git
- Link in question: https://github.com/orgs/SENATOROVAI/teams/senatorov-team

## Screenshots
![image](https://github.com/user-attachments/assets/93c607c9-7569-4d5d-a17f-ae851a6c42f4)

## Environment
- Browser: Google Chrome Версия 129.0.6668.101 (Официальная сборка), (64 бит)
- OS: Windows 10 Домашняя 22H2
- Python 3.11.9

## Suggested Solution
Consider updating the link to the correct team subscription URL or providing alternative instructions for team subscription.

**Comment by kypena** [comment]
@Nayil-Nord тебе надо зайти на https://github.com/orgs/SENATOROVAI/people . Там коллеги. Проваливаешься в кажого и нажимаешт follow. Ссылка у меня тоже не работает. Надеюсь помогла

**Comment by Nayil-Nord** [comment]
@kypena Thank you for your help! ✨

To ensure I understand correctly, can I update the hw.txt file like this?:
```txt
# 1) подписаться на коллег https://github.com/orgs/SENATOROVAI/teams/senatorov-team  
1) подписаться на коллег через https://github.com/orgs/SENATOROVAI/people

**Comment by Nayil-Nord** [comment]
@ruslansenatorov  прошу подключиться к обсуждению

**Comment by ruslansenatorov** [comment]
done

**Comment by ruslansenatorov** [comment]
ОЧЕНЬ КРУТО ОФОРМИЛ ИШЬЮС!

**Comment by ruslansenatorov** [comment]
> @kypena Thank you for your help! ✨
> 
> To ensure I understand correctly, can I update the hw.txt file like this?:
> 
> ```
> # 1) подписаться на коллег https://github.com/orgs/SENATOROVAI/teams/senatorov-team  
> 1) подписаться на коллег через https://github.com/orgs/SENATOROVAI/people
> ```

try again

**Comment by Nayil-Nord** [comment]
Обновление статуса: ✅ Проблема решена

@ruslansenatorov  @kypena   Спасибо! Ссылка https://github.com/orgs/SENATOROVAI/teams/senatorov-team теперь работает корректно.
Похоже, были обновлены права доступа.

Выполненные действия:
1. Выявлена проблема: ошибка 404
2. Предложено альтернативное решение: использование ссылки /people
3. Исходная ссылка исправлена: доступ предоставлен
4. Issue можно закрыть

Спасибо. 
Помечаю этот issue как решенный.

**Comment by Nayil-Nord** [comment]
Closing this issue as resolved ✅
- Original link is now working

**Comment by Nayil-Nord** [comment]
Если вы не видите кнопку "Close issue":

Проверьте, есть ли у вас права на закрытие issues
