### ISSUE TITLE
Подскажите плиз как правильно сделать принт  закомментированных строчек (см строчки 27 - 42) 

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#21]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a full screenshot and write what did you do to fix the problem?

![image](https://github.com/user-attachments/assets/1efc26f4-137e-44cf-b4a1-2334941392ba)

### Error from the terminal / Code

https://github.com/SENATOROVAI/DataScience-Nayil/blob/fc9a7bc9dd384ec5e2328f58f769858619b9f676/Python/learning_lab/probability_rules.py#L27-L42

### Expected behavior

Раскомментировать и распечатать строчки 

### Actual behavior

Возникают ошибки. Закомментировал. Подскажите плиз

**Comment by Umekko** [comment]
Accepted

**Comment by Umekko** [comment]
А в чем собственно ошибка ?

**Comment by Nayil-Nord** [comment]
Я постараюсь завтра воспроизвести свою ошибку,  пришлю информацию)

**Comment by Nayil-Nord** [comment]
@Umekko Спасибо.  Я кажется понял как нужно выводить большой текст.

**Comment by Umekko** [comment]
> @Umekko Спасибо.  Я кажется понял как нужно выводить большой текст. 

Думаю будет полезно здесь показать :)

**Comment by Nayil-Nord** [comment]
В коде: 
![image](https://github.com/user-attachments/assets/261f8ddb-9d2f-473b-8ab6-50e8fd8bc6ab)


На выходе: 
![image](https://github.com/user-attachments/assets/5ee3e304-bdc9-418c-89de-6829d60f702c)

**Comment by Nayil-Nord** [comment]
Главное ты показал рабочий принцип. А его дальше адаптирую, если  что.

**Comment by ruslansenatorov** [comment]
> Главное ты показал рабочий принцип. А его дальше адаптирую, если что.

вообще то я показывал в своём видео этот способ.
