### ISSUE TITLE
Доделать: Нужно добавить в конспект код

### ISSUE THREAD

**Issue by kypena** [SENATOROVAI/DataScience-Nayil#35]
### What would you like to share?

Пришлите коммит, которым Вы закрыли [ишьюз](https://github.com/SENATOROVAI/DataScience-Nayil/issues/28)

**Comment by Nayil-Nord** [comment]
@kypena Принял в работу.

**Comment by Nayil-Nord** [comment]
@kypena Добавил указанные два примера. Проверьте плиз

**Comment by Nayil-Nord** [comment]
https://github.com/SENATOROVAI/DataScience-Nayil/commit/b3cfe68b30be1293d2ff254d8b1dfb95bc8aa099

Хорошо, буду знать. Спасибо

**Comment by Nayil-Nord** [comment]
https://github.com/SENATOROVAI/DataScience-Nayil/commit/b3cfe68b30be1293d2ff254d8b1dfb95bc8aa099
