### ISSUE TITLE
[HELP] Проблема со стэшами ( подвисла судьба пулл реквеста - "Update release #5")

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#6]
### Attach a screenshot and write what did you do to fix the problem?

До семинара у меня было 57 стэшей, которые я хотел закрыть в процессе. В процессе обсуждения мы разбирали [пул реквест](https://github.com/SENATOROVAI/DataScience-Nayil/pull/5)  на моем репозитории. Я осознал, что мне следовало остановить обсуждение пул реквеста на моем примере, чтобы не усложнять ситуацию. Теперь я понимаю, что важно не только делать в кошке пулл перед коммитами, но и обязательно снимать стэши в первую очередь.

Когда на семинаре хотели принять пул реквест, мы дошли до кошки и попытались сделать fetch original, в какой -то момент количество стэшей увеличилось до 2005,  возможно это после изменений в .gitignore (включили .DS_Store). В какой-то момент кошка зависла и даже перестала открываться по ярлычку, перезагрузка не помогла, смог  открыл с командной строки и после этого стала открываться по ярлычку.  

В процессе мы попытались решить вопрос со стэшем, но не стали ничего трогать,потому что наткнулись на  два особо специальных файла: 
     github\workflows\build.yml
    github\workflows\pylint.yml

    
  Что мне с этим теперь делать? Помогите, пожалуйста.

![image](https://github.com/user-attachments/assets/fa0d5915-ae8c-4a5b-8c4a-61f3d9fae0ef)

![image](https://github.com/user-attachments/assets/ba9a21ef-640e-407a-afee-36d7fdab92b2)

### Error from the terminal / Code

PS C:\Users\ABA\Documents\github\DataScience-Nayil> git status
On branch main
Your branch is behind 'origin/main' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .github/.DS_Store
        new file:   CONTRIBUTING.md
        new file:   DIRECTORY.md
        new file:   LICENSE.md
        modified:   README.md
        new file:   __MACOSX/._.github
        new file:   __MACOSX/._.pre-commit-config.yaml
        new file:   __MACOSX/.github/._.DS_Store
        new file:   __MACOSX/.github/._ISSUE_TEMPLATE
        new file:   __MACOSX/.github/._dependabot.yml
        new file:   __MACOSX/.github/._pull_request_template.md
        new file:   __MACOSX/.github/._stale.yml
        new file:   __MACOSX/.github/._workflows
        new file:   __MACOSX/.github/ISSUE_TEMPLATE/._bug_report.yml
        new file:   __MACOSX/.github/ISSUE_TEMPLATE/._config.yml
        new file:   __MACOSX/.github/ISSUE_TEMPLATE/._feature_request.yml
        new file:   __MACOSX/.github/ISSUE_TEMPLATE/._other.yml
        new file:   __MACOSX/.github/workflows/._.DS_Store
        new file:   __MACOSX/.github/workflows/._build.yml
        new file:   __MACOSX/.github/workflows/._directory_writer.yml
        new file:   github/.github/.DS_Store
        new file:   github/.github/ISSUE_TEMPLATE/bug_report.yml
        new file:   github/.github/ISSUE_TEMPLATE/config.yml
        new file:   github/.github/ISSUE_TEMPLATE/feature_request.yml
        new file:   github/.github/ISSUE_TEMPLATE/other.yml
        new file:   github/.github/dependabot.yml
        new file:   github/.github/pull_request_template.md
        new file:   github/.github/stale.yml
        new file:   github/.github/workflows/.DS_Store
        new file:   github/.github/workflows/build.yml
        new file:   github/.github/workflows/directory_writer.yml
        new file:   github/.github/workflows/project_euler.yml
        new file:   github/.github/workflows/pylint.yml
        new file:   github/.github/workflows/ruff.yaml
        new file:   github/.github/workflows/sphinx.yml
        new file:   github/__MACOSX/._.github
        new file:   github/__MACOSX/.github/._.DS_Store
        new file:   github/__MACOSX/.github/._ISSUE_TEMPLATE
        new file:   github/__MACOSX/.github/._dependabot.yml
        new file:   github/__MACOSX/.github/._pull_request_template.md
        new file:   github/__MACOSX/.github/._stale.yml
        new file:   github/__MACOSX/.github/._workflows
        new file:   github/__MACOSX/.github/ISSUE_TEMPLATE/._bug_report.yml
        new file:   github/__MACOSX/.github/ISSUE_TEMPLATE/._config.yml
        new file:   github/__MACOSX/.github/ISSUE_TEMPLATE/._feature_request.yml
        new file:   github/__MACOSX/.github/ISSUE_TEMPLATE/._other.yml
        new file:   github/__MACOSX/.github/workflows/._.DS_Store
        new file:   github/__MACOSX/.github/workflows/._build.yml
        new file:   github/__MACOSX/.github/workflows/._directory_writer.yml
        new file:   github/__MACOSX/.github/workflows/._project_euler.yml
        new file:   github/__MACOSX/.github/workflows/._pylint.yml
        new file:   github/__MACOSX/.github/workflows/._ruff.yaml
        new file:   github/__MACOSX/.github/workflows/._sphinx.yml
        new file:   pre-commit-1.0.0/CONTRIBUTING.md
        new file:   pre-commit-1.0.0/README.md

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
        both modified:   .github/workflows/build.yml
        deleted by us:   .github/workflows/pylint.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .mypy_cache/

### Expected behavior

1. решение стэшей
2. пулл реквест

### Actual behavior

- не принятый пул реквест - https://github.com/SENATOROVAI/DataScience-Nayil/pull/5
- Количество измененных файлов выросло с 57 до 2005
  - Непонятно что делать с особо  специальными файлами ( на семинаре не стали их трогать без Руслана, остановились):
    ```
    github\workflows\build.yml
    github\workflows\pylint.yml
    ```

**Comment by Nayil-Nord** [comment]
в архиве два файла-стэша из кошки :
pylint.yml
build.yml

![image](https://github.com/user-attachments/assets/341d8ca2-4773-4836-91a1-1ae3c9a2ad44)

[workflows.zip](https://github.com/user-attachments/files/17531544/workflows.zip)

**Comment by ruslansenatorov** [comment]
1.  Файлы под удаление
 2. Пройти несколько заданий курса https://t.me/c/1937296927/3602/5714
 3. Новый формат апдейтов https://t.me/c/1937296927/3602/26077
