### ISSUE TITLE
[QUESTION] Уточнение процесса работы с pull request на удаленном и локальном репозитории

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#7]
## Моё начальное гипотетическое представление до семинара
1. Принятие pull request возможно:
  - На локальном репозитории
  - На удаленном репозитории
  - Особенно если нет возможности работать с локальным

2. Проверка работоспособности нового релиза:
  - Предполагал возможность проверки на удаленном репозитории и критерий успешной установки pull request через удаленный репозиторий: 10 successful checks при раскрытии галочки
  - Фактически увидел только 3 checks (признак старой версии релиза)

## Новое понимание после семинара
- Pull request можно принять только через локальный репозиторий
- Необходима работа через локальные инструменты (например, GitHub Desktop)

## Вопросы для уточнения
1. Верно ли, что pull request нельзя принять только на удаленном репозитории?
2. Правильно ли я понял необходимость использования для pull request  исключительно локального репозитория?
3. Как интерпретировать разное количество successful checks (10 vs 3) ? 

### Error from the terminal / Code

кода нет

### Expected behavior

- Предполагал возможность проверки на удаленном репозитории и критерий успешной установки pull request через удаленный репозиторий: 10 successful checks при раскрытии галочки

### Actual behavior

работа pull request через локальные инструменты (например, GitHub Desktop)

**Comment by Nayil-Nord** [comment]
## Заметка о неожиданном поведении checks

Хочу обратить внимание на странное поведение:
1. Pull request все еще не принят
2. Но на удаленном репозитории внезапно появились все 10 галочек проверок
  - Во время семинара их было только 3
  - Изменение произошло само, без видимых причин

Как это интерпретировать? Особенно учитывая, что никаких действий с pull request не производилось.

![image](https://github.com/user-attachments/assets/f9b054df-3d10-4d6c-97ed-e21e8db00bb4)

**Comment by ruslansenatorov** [comment]
Новое понимание после семинара

    Pull request можно принять только через локальный репозиторий - НЕПРАВДА, АПРУВ И СЛИЯНИЕ мы делаем в гитхабе 
    Необходима работа через локальные инструменты (например, GitHub Desktop) - НЕПРАВДА, всё что нужно это консоль - https://t.me/c/1937296927/3602/5714



1. Гитхаб - удаленный репозитории
2. Пул принял, пофиг что на локалку не грузит из-за конфликта файлов, тебе надо его решить
3.
