### ISSUE TITLE
# Неясная логика в подсчете вариантов в задаче № 7 о пассажирах лифта

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#8]
### Hash commit / link

https://github.com/SENATOROVAI/DataScience-Nayil/blob/main/Math/probability_theory/mathprofi/classical_probability_problems.ipynb

## Что я сделал для решения проблемы:

1. **Подготовительные действия:**
   - Создал файл [`classical_probability_problems.ipynb`](https://github.com/SENATOROVAI/DataScience-Nayil/blob/main/Math/probability_theory/mathprofi/classical_probability_problems.ipynb)
   - Добавил в него задачи по теории вероятностей
   - Выделил проблемную задачу №7 (задача о лифте)

2. **Попытки понять задачу:**
   - Изучил условие задачи
   - Проанализировал данное решение
   - Выявил конкретные места, которые вызывают непонимание

3. **Текущие шаги:**
   - Создаю этот issue для структурирования проблемы
   - Надеюсь на эффект свидетеля (когда формулировка проблемы помогает её понять)
   - Планирую привлечь коллег для обсуждения

## Задача 7

В лифт 20-этажного дома на первом этаже зашли 3 человека. Найти вероятность того, что:
- а) они выйдут на разных этажах
- б) двое выйдут на одном этаже
- в) все выйдут на одном этаже

### Решение:

Всего исходов: 19³ = 6859 (19 этажей, не считая первый, для каждого из трех пассажиров)

а) Размещение по разным этажам:
P(разные) = 19 × 18 × 17 / 6859 = 5814/6859 ≈ 0.848

в) Все на одном этаже:
P(один) = 19/6859 ≈ 0.003

б) Двое на одном этаже:
P(два) = 1 - P(разные) - P(один) = 1026/6859 ≈ 0.149

### Expected behavior

Как развить интуицию для понимания таких неявных условий в задачах по теории вероятностей? Может есть какие-то общие правила или подходы?

Хотелось бы получить:
1. Объяснение логики задачи
2. Рекомендации по распознаванию неявных условий
3. Пошаговое объяснение почему именно так считаются варианты выхода

Я вроде начинаю понимать  формулы и последующие операции, но изначально не могу идентифицировать проблему и распознать условие.

### Actual behavior

В условии задачи должно быть явно указано, почему пассажиры не могут выйти на первом этаже.  Почему 19, а не 20?   19³ = 6859 возможных исходов

Почему при поиске вероятности выхода на разных этажах (а):
Первый пассажир: 19 вариантов  . Почему 19?
Второй пассажир: 18 вариантов (кроме этажа первого)   Почему 18?
Третий пассажир: 17 вариантов (кроме этажей первых двух)   Почему 17?

**Comment by ruslansenatorov** [comment]
@Ntashus прими в работу

**Comment by VIVALDI142857** [comment]
"Хотелось бы получить:

Объяснение логики задачи
Рекомендации по распознаванию неявных условий
Пошаговое объяснение почему именно так считаются варианты выхода"

1. В пункте а нам нужно посчитать вероятность того, что каждый из них выйдет на этаже отличном от другого - то есть для каждого свой этаж, и если один уже вышел на одном этаже, то следующий человек не может выйти на том же этаже.
Первым, что нужно посчитать это полная группа - то есть - сколько всего есть вариантов выхода без каких-либо условий

Давайте это сделаем:
Всего 3 человека и для каждого есть 19 (в российских реалиях обычно первый этаж не является жилым, но думаю, никто бы не предъявил, если бы мы посчитали с 20 этажом) вариантов выхода - 19 * 19 * 19 = 6859

Следующим действием станет подсчет количества возможных вариантов с выходом людей на разных этажах:

**Логический подход:*********************************************

Для первого количество вариантов выхода = 19

Для второго на один меньше, так как один этаж уже занят вышедшим пассажиром лифта = 19 - 1 = 18

Для третьего остается еще на один этаж меньше, так как уже два этажа заняты - 19 - 2 = 17

Перемножаем, так как можем заменить умножение на логическое  "и", а логическое "или", обычно представляющее собой сложение вероятностей или объединение множеств, здесь не подходит:
Первый выйдет на 1 из 19, и второй выйдет на 1 из 18, и третий выйдет на одном из 17.

19 * 18 * 17 = 5814

5814 / 6859 = 0.8476454293628809 - итоговая вероятность.

**Подход с точки зрения комбинаторики*****************************************************************

Сперва нужно кое-что понять: посмотрите на разницу в формулах сочетания и размещения:

Разница в том, что в знаменателе размещения отсутствует деление на n! - в нашем случае это проявляется так:

Сначала числом сочетаний всеми возможными способами выбираем три этажа из 19 (для трех человек)
19C3 = 969

А потом умножаем на все возможные варианты переставить трех человек - 3! = 6 - так как они могут выходить в абсолютно разном порядке.

969 * 6 = 5814

5814 / 6859 = 0.8476454293628809 - итоговая вероятность.

Надеюсь, с пунктом  а все понятно

Пункт Б)

Двое выйдут на одном этаже:

Как интерпретировать этот случай?

Что ж, если двое выйдут на одном и том же этаже, то третий выйдет на другом, и это надо учесть.

Любые два человека из лифта могут выйти на одном этаже, найдем количество возможных групп людей числом сочетаний

Выбираем группу из двух человек всеми способами:

3C2 = 3

Для третьего остается 18 вариантов этажей

Считаем результат (так же используем умножение, так как подходит логическое "и"): 3 * 19  * 18 = 1026
Вероятность: 1026 / 6859 = 0.149

Пункт в) все выйдут на одном этаже

В этом случае порядок выхода людей непринципиален, так как итог от этого не поменяется, а это значит, что мы можем узнать вероятность просто подсчитав количество возможных вариантов этажей для выхода всех:

Таких 19 штук, так как всего 19 этажей:

19 / 6859 = 0.002770083102493075

**Comment by Nayil-Nord** [comment]
Спасибо
