### ISSUE TITLE
[QUESTION] Предложение по организации структуры папок для учебных материалов

### ISSUE THREAD

**Issue by Nayil-Nord** [SENATOROVAI/DataScience-Nayil#9]
## Текущая структура (из hw.txt, строчка 59):
Python/clean-code/номер_главы_название_главы.ipynb
Пример: сhapter_1_error_processing.ipynb

## Предлагаемая структура:
[github/DataScience-Nayil/Math/remember_all_emelin/chapter_02_equations_and_inequalities/](https://github.com/SENATOROVAI/DataScience-Nayil/tree/main/Math/remember_all_emelin/chapter_02_equations_and_inequalities)

где папка `chapter_02_equations_and_inequalities` содержит:
- Конспект
- Задачи
- Пояснительные материалы
- Другие связанные файлы

## Цели изменения
1. Разделение разных типов контента по подпапкам 
(конспект в один день, задачи в другой день, вопросы-обсуждения в 3й день)

## Вопросы
1. Не нарушит ли такая структура существующую систему?
2. Будет ли корректно работать автоматическая документация в README?
3. Соответствует ли это общим принципам организации репозитория?

**Comment by ruslansenatorov** [comment]
не надо разделять, всё должно быть в одном ноутбуке

**Comment by Nayil-Nord** [comment]
https://github.com/SENATOROVAI/DataScience-Nayil/blob/fb2356c52e7e0257545b30bc9e37a016ae693682/hw.txt#L8-L10
